---
- name: Include os distro/family specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars

- name: Set htpasswd packages
  set_fact:
    htpasswd_packages: "{{ __htpasswd_packages }}"
  when: htpasswd_packages | length == 0
