---
- name: Converge
  hosts: all
  vars:
    htpasswd_files:
      - path: /root/passwd
        owner: root
        group: root
        mode: "0600"
        users:
          - username: john.doe
            password: 123456789

          - username: foo
            password: 123456789
            crypt_scheme: des_crypt

          - username: bar
            password: hello_world!
            crypt_scheme: plaintext

      - path: /opt/another_passwd_file
        owner: root
        group: root
        mode: "0700"
        users:
          - username: devops
            password: 123456789

          - username: engineers
            password: 123456789
            crypt_scheme: des_crypt

          - username: another_user
            password: p4ssw0rd!
            crypt_scheme: plaintext

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
